package com.submitform.submitform.Controller;

import com.submitform.submitform.Entity.Task_tb;
import com.submitform.submitform.TaskRepository;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import org.springframework.beans.factory.annotation.Autowired;

import java.util.Date;

@Controller
public class TaskController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private TaskRepository userRepository;

    @GetMapping("/greeting")
    public String greetingForm(Model model) {
        model.addAttribute("user", new Task_tb());
        return "greeting";
    }

    @PostMapping("/greeting")
    public String greetingSubmit(@ModelAttribute Task_tb task) {

        Task_tb newUser = new Task_tb();

        newUser.setTask_name(task.getTask_name());
        newUser.setTask_context(task.getTask_context());
        newUser.setTask_type(task.getTask_type());
        Date date = new Date();
        task.setCreate_time(date);
        task.setUpdate_time(date);
        userRepository.save(task);


        return "result";

    }

    @GetMapping("/all")
    public String getMessage(Model model) {

        Iterable<Task_tb> users = userRepository.findAll();

        model.addAttribute("users", users);
        return "all";
    }

}